FROM drupal:7

# required if you want the sqlite db to persist
VOLUME ["/var/www/html/sites/default/files/"]

# can be used in conjunction with a runtime command like:
# docker run -it -p 80:80 -v /temp/drupal/sqlite:/var/www/html/sites/default/files {tag_name}
